// Code generated by "stringer -type Code -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeGeneralErr - -1]
	_ = x[CodeRepeatInit-10001]
}

const (
	_Code_name_0 = "unknow error"
	_Code_name_1 = "repeat init exception"
)

func (i Code) String() string {
	switch {
	case i == -1:
		return _Code_name_0
	case i == 10001:
		return _Code_name_1
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
